<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function add_action() in /app/public/wp-content/themes/nighspot/customize-pro/class-customize.php on line <i>41</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function add_action() in /app/public/wp-content/themes/nighspot/customize-pro/class-customize.php on line <i>41</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>359624</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/app/public/wp-content/themes/nighspot/customize-pro/class-customize.php' bgcolor='#eeeeec'>.../class-customize.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>359624</td><td bgcolor='#eeeeec'>Nighspot_Customize::get_instance(  )</td><td title='/app/public/wp-content/themes/nighspot/customize-pro/class-customize.php' bgcolor='#eeeeec'>.../class-customize.php<b>:</b>85</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>360064</td><td bgcolor='#eeeeec'>Nighspot_Customize->setup_actions(  )</td><td title='/app/public/wp-content/themes/nighspot/customize-pro/class-customize.php' bgcolor='#eeeeec'>.../class-customize.php<b>:</b>20</td></tr>
</table></font>
