<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function plugins_url() in /app/public/wp-content/plugins/all-in-one-wp-migration/all-in-one-wp-migration.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function plugins_url() in /app/public/wp-content/plugins/all-in-one-wp-migration/all-in-one-wp-migration.php on line <i>48</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0010</td><td bgcolor='#eeeeec' align='right'>359304</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/app/public/wp-content/plugins/all-in-one-wp-migration/uninstall.php' bgcolor='#eeeeec'>.../uninstall.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0010</td><td bgcolor='#eeeeec' align='right'>359616</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/app/public/wp-content/plugins/all-in-one-wp-migration/all-in-one-wp-migration.php'</font> )</td><td title='/app/public/wp-content/plugins/all-in-one-wp-migration/uninstall.php' bgcolor='#eeeeec'>.../uninstall.php<b>:</b>29</td></tr>
</table></font>
